Draft: Prepare ldapmonitor for Zabbix triggers
SURFscz/SRAM-deploy pull request #385
Opened 2022-12-02 15:38 UTC by mrvanes

2022-12-02 15:46 UTC, mrvanes commented
Bijbehorende Zabbix triggers
Stale monitoring data:
```now()-last(/ldap1/system.run["/opt/ldapmonitor/getmonitor.py time"])>100```

CSN difference too big:
```abs(last(/ldap1/system.run["/opt/ldapmonitor/getmonitor.py csn"],#1) - last(/ldap2/system.run["/opt/ldapmonitor/getmonitor.py csn"],#1))>10```

Hashes out of sync:
```last(/ldap1/system.run["/opt/ldapmonitor/getmonitor.py hash"],#1)<>last(/ldap2/system.run["/opt/ldapmonitor/getmonitor.py hash"],#1)```

2023-01-13 08:44 UTC, baszoetekouw requested changes

2023-01-13 08:44 UTC, baszoetekouw commented on roles/ldap/tasks/main.yml
> +
Dit lijkt me niet in deze PR thuishoren?
Hebben we deze change nog wel nodig?  Ik dacht dat we dit geneuzel na de zomer helemaal gefixed hadden.

2023-01-13 08:57 UTC, baszoetekouw approved these changes

2023-01-13 08:57 UTC, baszoetekouw commented on roles/ldap/tasks/main.yml
> +
blijkbaar wel echt nodig, als ik de commits zo zie?
Kan ook geen kwaad verder.

2023-01-13 08:57 UTC, merged